debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
{% if https_only %}
    [entryPoints.http.redirect]
    entryPoint = "https"
{% endif %}
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]

[Docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "{{ domain }}"
  watch = true
  exposedByDefault = false

[acme]
  email = "{{ admin_email }}"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
{% if use_dns_challenge %}
  acmeLogging = true
  onDemand = false

[acme.dnsChallenge]
  provider = "{{ dns_provider }}"
  delayBeforeCheck = 300
[[acme.domains]]
  main = "{{ domain }}"
{% else %}
[[acme.domains]]
  main = "*.{{ domain }}"
  sans = ["{{ domain }}"]
{% endif %}
