debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.proxyProtocol]
      insecure = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]

[Docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "curl.fun"
  watch = true
  exposedByDefault = false

[acme]
  email = "kebertxela86@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  acmeLogging = true
  onDemand = false #create certificate when container is created

[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 60

[[acme.domains]]
  main = "*.curl.fun"
  sans = ["curl.fun"]
